DocumentRoot "/app"

LoadModule mpm_prefork_module modules/mod_mpm_prefork.so

<Directory "/app">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

# The DefaultRuntimeDir directive sets the directory in which the server will create various run-time files (shared memory, locks, etc.). If set as a relative path, the full path will be relative to ServerRoot.
DefaultRuntimeDir /tmp/httpd

# Logging to Docker Streams
ErrorLog /proc/self/fd/2
CustomLog /proc/self/fd/1 combined
